# ---------------------------------------------------------
# Model parameters
# ---------------------------------------------------------

model:
  version: "0.1"
  note: "FIRST MODEL with YAML"
  test_size: 0.33

classifier:
  param_grid:
      clf__n_estimators: [25,50,75,100]
      clf__criterion: ['gini', 'entropy'] 
      clf__max_depth: [2,4,6]